spring:
  application:
    name: store

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Formato: ${VARIABLE:VALOR_POR_DEFECTO}
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:techlabdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  sql:
    init:
      mode: always
      #data-locations: classpath:products.sql, classpath:clients.sql

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
