# --- Custom App Configuration ---
app.base-url=${APP_BASE_URL:http://localhost:8080}
app.admin.username=${APP_ADMIN_USERNAME:admin}
app.admin.password=${APP_ADMIN_PASSWORD:admin1234}
app.font.default=inter.ttf

# --- Spring MVC & Static Resources ---
spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=file:${UPLOAD_DIR:/app/uploads}/

# --- General Application Settings ---
spring.application.name=store
spring.main.allow-bean-definition-overriding=true
spring.main.lazy-initialization=true

# --- Database / Datasource Configuration ---
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}
spring.datasource.url=${DB_URL:jdbc:mysql://db:3306/techlabdb}
spring.datasource.username=${DB_ROOT_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10

# --- SQL Initialization ---
spring.sql.init.mode=always
spring.sql.init.data-locations=

# --- JPA / Hibernate Configuration ---
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.MySQLDialect}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show-sql=true

# --- H2 Console (Disabled) ---
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console

# --- Server Configuration ---
server.port=8080




